// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-EppjIU6eNrQKpjAypXXHvHPykGHMCV8',
    appId: '1:999018777322:web:db9cf1dcfeb9b04d676593',
    messagingSenderId: '999018777322',
    projectId: 'smart-hostel-companion-cep',
    authDomain: 'smart-hostel-companion-cep.firebaseapp.com',
    storageBucket: 'smart-hostel-companion-cep.firebasestorage.app',
    measurementId: 'G-4X7FD32BE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjk-T16ZGHa2UMb7uQTHA9A7rrxXoi2k',
    appId: '1:999018777322:android:5fcdd13646bc2009676593',
    messagingSenderId: '999018777322',
    projectId: 'smart-hostel-companion-cep',
    storageBucket: 'smart-hostel-companion-cep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi8236zmkJIl5k3Nk3hbB0A2or9WRh_pk',
    appId: '1:999018777322:ios:fc616ef005b5b0e0676593',
    messagingSenderId: '999018777322',
    projectId: 'smart-hostel-companion-cep',
    storageBucket: 'smart-hostel-companion-cep.firebasestorage.app',
    iosBundleId: 'com.example.smartHostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi8236zmkJIl5k3Nk3hbB0A2or9WRh_pk',
    appId: '1:999018777322:ios:fc616ef005b5b0e0676593',
    messagingSenderId: '999018777322',
    projectId: 'smart-hostel-companion-cep',
    storageBucket: 'smart-hostel-companion-cep.firebasestorage.app',
    iosBundleId: 'com.example.smartHostelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-EppjIU6eNrQKpjAypXXHvHPykGHMCV8',
    appId: '1:999018777322:web:f265b765a146183c676593',
    messagingSenderId: '999018777322',
    projectId: 'smart-hostel-companion-cep',
    authDomain: 'smart-hostel-companion-cep.firebaseapp.com',
    storageBucket: 'smart-hostel-companion-cep.firebasestorage.app',
    measurementId: 'G-P6BB7S4R3P',
  );
}
